[run_data]
filenames = [
    "jw04426-o001_t001_nirspec_g235m-f170lp/jw04426-o001_t001_nirspec_g235m-f170lp_x1d.fits",
    "jw04426-o001_t001_nirspec_g140m-f100lp/jw04426-o001_t001_nirspec_g140m-f100lp_x1d.fits"]
name = "gnz11_final"

[run_setup]
gnz11_split = 1.65978
gnz11_min = 0.99

[analysis]
width_factor = 150.0
padding = 1e-8
num_knots = 5
chisq_step = 4.0 
limit_guess = [1e-5, 1e-3]
max_clip_iters = 100
clipping_factor = 3.0
pc_step_factor = 5 
Ntrials = 100
Nbins = 15
power_threshold = 0.1587
Nthreads = 4
inflate = 100   