[run_data]
filenames = = [
    "jw01039-o005_t001_miri_ch4-shortmediumlong/jw01039-o005_t001_miri_ch4-shortmediumlong_x1d.fits",
    "jw01039-o005_t001_miri_ch1-shortmediumlong/jw01039-o005_t001_miri_ch1-shortmediumlong_x1d.fits",
    "jw01039-o005_t001_miri_ch2-shortmediumlong/jw01039-o005_t001_miri_ch2-shortmediumlong_x1d.fits",
    "jw01039-o005_t001_miri_ch3-shortmediumlong/jw01039-o005_t001_miri_ch3-shortmediumlong_x1d.fits"]

